name = "dark-voice-0a31discount-furniture-lightspeed-readonly"
main = "src/index.js"
compatibility_date = "2026-04-29"

[vars]
LS_DOMAIN_PREFIX = "discountfurniture"
LS_WRITE_ENABLED = "true"

[[d1_databases]]
binding = "DB"
database_name = "df-description-history"
database_id = "b7106c3e-4ffa-4015-b19e-041e88797ec0"
